name: waymo_NOTR
channels:
  - defaults
  - pytorch 
dependencies:
  - ca-certificates=2024.11.26  #
  - libffi=3.4.4  
  - ncurses=6.4 
  - openssl=3.0.15 
  - pip=24.2
  - python=3.8.20  
  - readline=8.2 
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0 
  - xz=5.4.6 
  - zlib=1.2.13  
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==3.0.0
      - attrs==24.3.0
      - backcall==0.2.0
      - bidict==0.23.1
      - black==24.8.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - cityscapesscripts==2.2.4
      - click==8.1.8
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.12
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diff-gaussian-rasterization==0.0.0
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - flask==3.0.3
      - fonttools==4.55.3
      - fsspec==2024.12.0
      - fvcore==0.1.5.post20221221
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.68.1
      - h5py==3.11.0
      - huggingface-hub==0.27.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - imgaug==0.4.0
      - imgviz==1.7.5
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.9
      - ipdb==0.13.13
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multiscaledeformableattention==1.0
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - numpy==1.23.5
      - nvdiffrast==0.3.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.0.3
      - panopticapi==0.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.24.1
      - plyfile==1.0.3
      - portalocker==3.0.0
      - prompt-toolkit==3.0.48
      - protobuf==3.19.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycocotools==2.0.7
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - roma==1.5.1
      - rpds-py==0.20.1
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - segment-anything==1.0
      - shapely==2.0.6
      - simple-knn==0.0.0
      - simple-waymo-open-dataset-reader==0.0.0
      - six==1.17.0
      - stack-data==0.6.3
      - submitit==1.5.2
      - supervision==0.25.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.12
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==1.13.1  
      - torchaudio==0.13.1  
      - torchmetrics==1.5.2
      - torchvision==0.14.1  
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.20.2